services:
 mysql:
    image: mysql/mysql-server:8.0
    volumes:
        - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - "3308:3306"